### ISSUE TITLE
Section 2: Files and content issue

### ISSUE THREAD

**Issue by sb1975** [PacktPublishing/Mastering-REST-APIs-with-FastAPI#1]
The Files are not uploaded with correct content as explained in video.

Also the correct code to make the REST API work using /post will be this :

@app.post("/post", response_model=UserPost)
async def create_post(post: UserPostIn):
    data = post.dict()
    last_record_id = len(post_table)
    new_post = {**data, "id": last_record_id}
    post_table[last_record_id] = new_post
    return new_post

Its surprising how it worked in the Video, which is wrong.

**Comment by Sonakshis** [comment]
Hi @sb1975 
We have updated the course. 
Happy learning!
